services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.516.1-lts-jdk21
    restart: always
    ports:
      - "9999:8080"
    networks:
      - jenkins_network
    volumes:
      - jenkins:/var/jenkins_home
  agent:
    container_name: build-agent
    image: biswasakash/docker-ssh-agent:latest
    environment:
      - JENKINS_PUBLIC_KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM62ZFyBTRyr6tbGzpZcxfsBtofJQ0XXq3+VQspzLY4I akash@workstation
    privileged: true
    networks:
      - jenkins_network
volumes:
  jenkins:
networks:
  jenkins_network:
    external: true
    name: global-jenkins-network
