services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.516.1-lts-jdk21
    restart: always
    ports:
      - "9999:8080"
    networks:
      - jenkins_network
    volumes:
      - jenkins:/var/jenkins_home
  agent:
    container_name: agent
    image: jenkins/ssh-agent:latest-debian-jdk21
    restart: always
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM62ZFyBTRyr6tbGzpZcxfsBtofJQ0XXq3+VQspzLY4I akash@workstation
    networks:
      - jenkins_network
    volumes:
      - agent:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  jenkins_network:
    driver: bridge
volumes:
  jenkins:
  agent:
